import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { FaArrowLeft, FaStore } from "react-icons/fa";
import { useLocation } from "react-router-dom";
import api from "../api/axiosClient";
import { toast } from "react-toastify";

export default function EditStore() {
    const [form, setForm] = useState({
        name: "",
        ownerId: "",
        currency: "USD",
        templateId: "",
        commissionRate: "",
        domain: "",
        isPublished: false,
    });

    const location = useLocation();
    const queryParams = new URLSearchParams(location.search);
    const storeId = queryParams.get("id");

    // Fetch Store Data
    const { data, isLoading } = useQuery({
        queryKey: ["store", storeId],
        queryFn: async () => {
            const res = await api.get(`/stores/${storeId}`);
            return res.data;
        },
        enabled: !!storeId,
    });

    // Populate Form
    useEffect(() => {
        if (data) {
            setForm({
                name: data.name || "",
                ownerId: data.ownerId || "",
                currency: data.currency || "USD",
                templateId: data.templateId || "",
                commissionRate: data.commissionRate || "",
                domain: data.domain || "",
                isPublished: data.isPublished || false,
            });
        }
    }, [data]);

    const handleChange = (key, value) => {
        setForm((prev) => ({ ...prev, [key]: value }));
    };

    const saveStore = async () => {
        try {
            const payload = {
                name: form.name,
                ownerId: form.ownerId,
                currency: form.currency,
                templateId: form.templateId,
                commissionRate: Number(form.commissionRate),
                domain: form.domain,
                isPublished: form.isPublished,
                // slug is usually generated by backend or read-only
                slug: data?.slug
            };

            await api.put(`/stores/${storeId}`, payload);
            toast.success("Store updated successfully");
        } catch (err) {
            console.error("UPDATE STORE ERROR:", err);
            toast.error(err?.response?.data?.error || "Error updating store");
        }
    };

    if (isLoading) {
        return (
            <div className="w-full h-screen flex justify-center items-center bg-gray-50">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-black"></div>
            </div>
        )
    }

    return (
        <div className="w-full min-h-screen bg-gray-50 pb-20">
            {/* Header */}
            <div className="sticky top-0 z-20 bg-white/80 backdrop-blur-md border-b border-gray-200 px-4 py-4 md:px-8 mb-8">
                <div className="max-w-7xl mx-auto flex flex-col sm:flex-row justify-between items-center gap-4">
                    <div className="flex items-center gap-3 text-gray-600 hover:text-black transition-colors cursor-pointer" onClick={() => window.history.back()}>
                        <div className="p-2 rounded-full hover:bg-gray-100 transition-colors">
                            <FaArrowLeft />
                        </div>
                        <h1 className="text-2xl font-bold text-gray-900">Edit Store</h1>
                    </div>

                    <div className="flex gap-3 w-full sm:w-auto">
                        <button
                            onClick={() => window.history.back()}
                            className="flex-1 sm:flex-none px-6 py-2.5 rounded-xl border border-gray-300 font-semibold text-gray-700 hover:bg-gray-50 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            onClick={saveStore}
                            className="flex-1 sm:flex-none px-8 py-2.5 rounded-xl bg-black text-white font-bold hover:bg-gray-800 transition-all shadow-lg hover:shadow-xl transform active:scale-95"
                        >
                            Save Changes
                        </button>
                    </div>
                </div>
            </div>

            <div className="max-w-7xl mx-auto px-4 md:px-8 grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* LEFT COLUMN */}
                <div className="lg:col-span-2 space-y-8">

                    {/* Basic Info */}
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 md:p-8">
                        <div className="flex items-center gap-4 mb-6">
                            <div className="p-3 bg-gray-100 rounded-full">
                                <FaStore className="text-2xl text-gray-600" />
                            </div>
                            <h2 className="text-lg font-bold text-gray-900">Store Information</h2>
                        </div>

                        <div className="space-y-5">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">Store Name</label>
                                <input
                                    value={form.name}
                                    onChange={(e) => handleChange("name", e.target.value)}
                                    className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none"
                                    placeholder="Store Name"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">Owner ID</label>
                                <input
                                    value={form.ownerId}
                                    onChange={(e) => handleChange("ownerId", e.target.value)}
                                    className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none"
                                    placeholder="Owner ID"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">Custom Domain</label>
                                <input
                                    value={form.domain}
                                    onChange={(e) => handleChange("domain", e.target.value)}
                                    className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none"
                                    placeholder="e.g. shop.example.com"
                                />
                            </div>
                        </div>
                    </div>

                    {/* Configuration */}
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 md:p-8">
                        <h2 className="text-lg font-bold text-gray-900 mb-6">Configuration</h2>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">Currency</label>
                                <select
                                    value={form.currency}
                                    onChange={(e) => handleChange("currency", e.target.value)}
                                    className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none cursor-pointer"
                                >
                                    <option value="USD">USD ($)</option>
                                    <option value="INR">INR (₹)</option>
                                    <option value="EUR">EUR (€)</option>
                                    <option value="GBP">GBP (£)</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-2">Commission Rate (%)</label>
                                <input
                                    type="number"
                                    value={form.commissionRate}
                                    onChange={(e) => handleChange("commissionRate", e.target.value)}
                                    className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none"
                                />
                            </div>
                        </div>
                        <div className="mt-5">
                            <label className="block text-sm font-semibold text-gray-700 mb-2">Template ID</label>
                            <input
                                value={form.templateId}
                                onChange={(e) => handleChange("templateId", e.target.value)}
                                className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none"
                            />
                        </div>
                    </div>
                </div>

                {/* RIGHT COLUMN */}
                <div className="space-y-8">
                    {/* Status */}
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                        <h2 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4">Status</h2>
                        <select
                            value={form.isPublished ? "Published" : "Draft"}
                            onChange={(e) => handleChange("isPublished", e.target.value === "Published")}
                            className="w-full bg-gray-50 border border-gray-200 rounded-xl px-4 py-3 focus:bg-white focus:ring-2 focus:ring-black focus:border-transparent transition-all outline-none cursor-pointer"
                        >
                            <option value="Published">Published</option>
                            <option value="Draft">Draft</option>
                        </select>
                        <p className="text-xs text-gray-500 mt-3">
                            {form.isPublished ? "This store is currently live and visible to customers." : "This store is hidden from customers."}
                        </p>
                    </div>

                    {/* Read Only Info */}
                    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
                        <h2 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4">System Info</h2>
                        <div className="space-y-3">
                            <div>
                                <label className="block text-xs font-semibold text-gray-500">Store ID</label>
                                <div className="text-sm font-mono bg-gray-50 p-2 rounded border border-gray-200 mt-1">{storeId}</div>
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-gray-500">Slug</label>
                                <div className="text-sm font-mono bg-gray-50 p-2 rounded border border-gray-200 mt-1">{data?.slug || "N/A"}</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}
